#Домашнє завдання до тем apply(), groupby(), pivot_table()

В цьому домашньому завданні продовжуємо працювати з набором даних `supermarket_sales.csv`.

0. Імпортуйте бібліотеку pandas та зчитайте дані у змінну `df` типу `pandas.DataFrame`.

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('drive/MyDrive/Python/Data/supermarket_sales.csv')

In [5]:
df.head(5)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3

1. Дослідимо, який філіал супермаркету ('Branch') є найприбутковішим. Для цього знайдіть сумарний прибуток за кожним філіалом і виявіть, який філіал має найвищий.

In [6]:
df.groupby('Branch')['gross income'].sum().sort_values(ascending=False)

Branch
C    5265.1765
A    5057.1605
B    5057.0320
Name: gross income, dtype: float64

2. В якому місті знайходиться філіал з найвищим прибутком? Може в тому місці нам розмітисти ще один магазин.  
Знайдіть відповідь за допомогою функціоналу Pandas.

In [106]:
df.groupby('City')['gross income'].sum().sort_values(ascending=False).head(1)

City
Naypyitaw    5265.1765
Name: gross income, dtype: float64

3.1. Створіть зводну таблицю, яка покаже, скільки покупок (інвойсів) було зроблено в кожній з філій (`Branch`) за різними категоріями товарів. Запишіть таблицю в змінну `invoices_by_category` і виведіть змінну на екран.
Ця таблиця допоможе проаналізувати, в якій філії купують найбільше товарів кожної з категорій.

In [7]:
invoices_by_category = df.pivot_table(index='Branch', columns='Product line', values='Invoice ID', aggfunc='count')
invoices_by_category

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Branch,,,,,,
A,60,51,58,47,65,59
B,55,62,50,53,50,62
C,55,65,66,52,45,45

Очікуваний результат:

![](https://drive.google.com/uc?export=view&id=1rueAdko6S3UxIHGtojetTxlES-EyM6Yb)

3.2. Використовуючи змінну `invoices_by_category` дайте відповідь програмно (тобто значення треба не просто знайти очима, а вивести за допомогою коду), в якому філіалі магазину (`Branch`) найбільше інвойсів із покупкою товарів категорії "Електронні аксесуари" (`Electronic accessories`)?

In [8]:
invoices_by_category['Electronic accessories'].sort_values(ascending=False).head(1)

Branch
A    60
Name: Electronic accessories, dtype: int64

4-6. **Творче завдання на розвиток аналітичного мислення**

Крок 1. Сформулюйте ТРИ питання (гіпотези) до наявних даних, які допомогли б вам зрозуміти, які користувачі що, де та коли найбільше/найменше купують, аби дати на основі цих гіпотез рекомендації бізнесу. Звісно питання мають бути не тими, на які ми вже відповіли в завданнях модулю.

Крок 2. Знайдіть відповіді на свої питання з допомогою функціоналу pandas.

Крок 3. Напишіть, як відповідь на це питання може бути використана для прийняття бізнес рішень.   
   
 Питання можуть бути будь-якої складності, але їх має бути 3. Кожне питання оцінюється як 1 завдання. Без виконання цього завдання ДЗ не приймається. Якщо є питання щодо виконання - пишіть у чат 🙌

**1. Чи залежить середній чек від типу покупця по різним категоріям товарів?**

Згідно отриманих результатів спостерігається ситуація, що середній чек по всім категоріям товарів окрім "Sports and travel" вищий по типу покупця "Member" ніж по "Normal". Велика різниця спостерігається між типами покупців по середньому чеку в категорії "Health and beauty". Дослідивши статистичні показники по кожному типу покупців можна зробити висновок, що у категорії "Health and beauty" покупці категорії Member демонструють систематично вищий чек порівняно зі звичайними покупцями Normal.

Середнє значення по двом типам покупців суттєво вище за медіану — це означає, що розподіл витягнутий вправо (є частина покупок з високим чеком, які "тягнуть" середнє вгору). Розрив зберігається і на 25-му, і на 75-му перцентилі між типами покупців з чого можна зробити висновок, що Member-покупці стабільно витрачають більше за Normal-покупців в цій категорії на всіх рівнях вартості покупки, а не тільки за рахунок outliers.

**Рекомендація для бізнесу:** оскільки Member вже органічно витрачають більше в цій категорії, варто розглянути персоналізовані пропозиції в категорії Health and beauty для учасників програми лояльності — там найбільший потенціал для крос-продажу та збільшення частоти покупок.

In [62]:
df.pivot_table(index='Product line', columns='Customer type', values='Total', aggfunc='mean').round(2)

Customer type           Member  Normal
Product line
Electronic accessories  314.08  324.34
Fashion accessories     306.09  304.15
Food and beverages      333.59  309.84
Health and beauty       353.85  295.73
Home and lifestyle      337.08  336.15
Sports and travel       324.53  340.36

In [99]:
df_selected_cols = df[['Customer type', 'Total', 'Gender', 'Payment', 'Product line']]

In [98]:
# статитистичні дані по категорії "Health and beauty" по типу покупця "Member"
df_selected_cols[
    (df_selected_cols['Product line'] == 'Health and beauty') & (df_selected_cols['Customer type'] == 'Member')].describe(percentiles=[0.01, 0.25, 0.50, 0.75, 0.99])

            Total
count   73.000000
mean   353.849856
std    247.284873
min     19.246500
1%      19.866420
25%    145.582500
50%    293.139000
75%    545.370000
99%    927.554880
max    950.250000

In [90]:
# статитистичні дані по категорії "Health and beauty" по типу покупця "Normal"
df_selected_cols[
    (df_selected_cols['Product line'] == 'Health and beauty') & (df_selected_cols['Customer type'] == 'Normal')].describe(percentiles=[0.01, 0.25, 0.50, 0.75, 0.99])

            Total
count   79.000000
mean   295.730373
std    226.148991
min     18.637500
1%      24.575250
25%    121.317000
50%    231.241500
75%    420.997500
99%    895.935600
max    922.635000

**2. Чи є залежність суми середнього чеку від гендеру та типу оплати?**

Згідно отриманих результатів можна спостерігати, що є залежність від гендеру, де видно, що жінки обирають дорожчі товари ніж чоловіки при незначній перевищеній середній кількості товару в чеку по всім способам оплат.

Credit card — спосіб оплати з найменшою гендерною різницею (+2.8%), де поведінка чоловіків і жінок схожа.

У способі оплати Ewallet жінки демонструють суттєво вищий чек порівняно з чоловіками: медіана перевищує чоловічу на 46.5% (299.89 проти 204.70). Це вказує на стійку та суттєву відмінність купівельної поведінки за гендером саме в цьому каналі оплати.

**Рекомендації для бізнесу:** перевірити гіпотезу, що жінки частіше використовують Ewallet саме для великих/планових покупок, а чоловіки — для дрібних/спонтанних; розглянути впровадження промо для способу оплати Ewallet для жіночої аудиторії.

In [96]:
df.pivot_table(index='Payment', columns='Gender', values=['Total', 'Quantity'], aggfunc='mean').round(2)

            Quantity         Total
Gender        Female  Male  Female    Male
Payment
Cash            5.64  5.37  334.35  317.42
Credit card     5.69  5.36  328.21  319.38
Ewallet         5.86  5.16  342.94  297.96

In [101]:
# статитистичні дані по способу оплати "Ewallet" по гендеру "Female"
df_selected_cols[
    (df_selected_cols['Payment'] == 'Ewallet') & (df_selected_cols['Gender'] == 'Female')].describe(percentiles=[0.01, 0.25, 0.50, 0.75, 0.99])

             Total
count   160.000000
mean    342.939188
std     238.812738
min      26.554500
1%       32.470410
25%     148.459500
50%     299.890500
75%     504.664125
99%     980.797650
max    1034.460000

In [102]:
# статитистичні дані по способу оплати "Ewallet" по гендеру "Male"
df_selected_cols[
    (df_selected_cols['Payment'] == 'Ewallet') & (df_selected_cols['Gender'] == 'Male')].describe(percentiles=[0.01, 0.25, 0.50, 0.75, 0.99])

             Total
count   185.000000
mean    297.961281
std     238.408915
min      13.419000
1%       19.724040
25%     106.501500
50%     204.697500
75%     446.439000
99%     932.120280
max    1023.750000

**3. Чи відрізняється середня ціна товару по категоріям між містами та яка середня кількість товару в 1 чеку по категоріям?**

Середня ціна одиниці товару в категорії "Health and beauty" в Yangon 49.86 помітно нижча, ніж у Naypyitaw (+12.2%) та Mandalay (+16.7%), при подібній середній кількості одиниць у чеку (5 - 6 штук). Це може вказувати на відмінності в асортименті або ціновому позиціонуванні категорії між містами.

Подібна ситуація спостерігається в місті Mandalay по категорії "Electronic accessories", де середня ціна за одиницю товару категорії нижча ніж в інших містах при продажах майже однакової кількості товару між містами.

**Рекомендація для бізнесу:** деталізувати аналіз на рівні окремих товарів категорії, перевірити вплив викидів та наявність цінових акцій в аналізованому періоді.

In [36]:
df.pivot_table(index='Product line', columns='City', values=['Unit price', 'Quantity'], aggfunc='mean').round(2)

                       Quantity                  Unit price
City                   Mandalay Naypyitaw Yangon   Mandalay Naypyitaw Yangon
Product line
Electronic accessories     5.75      6.05   5.37      49.85     55.81  54.87
Fashion accessories        4.79      5.26   5.16      54.84     59.74  56.67
Food and beverages         5.40      5.59   5.40      55.54     57.27  54.97
Health and beauty          6.04      5.33   5.47      58.19     55.97  49.86
Home and lifestyle         5.90      5.44   5.71      55.51     54.33  55.85
Sports and travel          5.19      5.89   5.64      59.68     55.11  55.61

In [23]:
df.groupby('City').agg({'Total': 'mean', 'Quantity': 'mean'}).round(2)

            Total  Quantity
City
Mandalay   319.87      5.48
Naypyitaw  337.10      5.58
Yangon     312.35      5.47